-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Filter2D is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC;
    p_kernel_val_0_V_1_read : IN STD_LOGIC_VECTOR (1 downto 0);
    p_kernel_val_0_V_2_read : IN STD_LOGIC_VECTOR (1 downto 0);
    p_kernel_val_1_V_0_read : IN STD_LOGIC_VECTOR (2 downto 0);
    p_kernel_val_1_V_2_read : IN STD_LOGIC_VECTOR (3 downto 0);
    p_kernel_val_2_V_0_read : IN STD_LOGIC_VECTOR (1 downto 0);
    p_kernel_val_2_V_1_read : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of Filter2D is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_43A : STD_LOGIC_VECTOR (10 downto 0) := "10000111010";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_438 : STD_LOGIC_VECTOR (10 downto 0) := "10000111000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_438 : STD_LOGIC_VECTOR (11 downto 0) := "010000111000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_FFE : STD_LOGIC_VECTOR (11 downto 0) := "111111111110";
    constant ap_const_lv12_FFD : STD_LOGIC_VECTOR (11 downto 0) := "111111111101";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv11_782 : STD_LOGIC_VECTOR (10 downto 0) := "11110000010";
    constant ap_const_lv12_780 : STD_LOGIC_VECTOR (11 downto 0) := "011110000000";
    constant ap_const_lv13_EFE : STD_LOGIC_VECTOR (12 downto 0) := "0111011111110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_data_stream_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln444_reg_1417 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln118_reg_1426 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_reg_1382 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_reg_1373 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_dst_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal and_ln512_reg_1447 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_reg_1447_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_2_reg_319 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1118_fu_330_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_reg_1334 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_1_fu_334_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_1_reg_1339 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_2_fu_338_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1118_2_reg_1344 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1118_4_fu_342_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1118_4_reg_1349 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln1118_3_fu_346_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1118_3_reg_1354 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1118_5_fu_350_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1118_5_reg_1359 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln443_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_V_fu_364_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_V_reg_1368 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln887_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln457_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln457_reg_1377 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_reg_1387 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_1_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_1_reg_1391 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_1_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln899_1_reg_1395 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln493_1_fu_564_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_1_reg_1402 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_2_fu_602_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_2_reg_1407 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_3_fu_640_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_3_reg_1412 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln444_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op143_read_state4 : BOOLEAN;
    signal ap_predicate_op150_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln444_reg_1417_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln444_reg_1417_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_656_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal and_ln118_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln118_reg_1426_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_fu_786_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal x_reg_1430 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln458_fu_794_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln458_reg_1435 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln457_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln457_reg_1440 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln457_reg_1440_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_fu_803_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_reg_1447_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_reg_1447_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln512_reg_1447_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal right_border_buf_0_19_reg_1451 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln493_fu_821_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln493_reg_1462 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_buf_0_val_4_addr_reg_1469 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_addr_reg_1475 : STD_LOGIC_VECTOR (10 downto 0);
    signal src_kernel_win_0_va_23_fu_940_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_23_reg_1481 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_23_reg_1481_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_24_fu_958_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_24_reg_1488 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_24_reg_1488_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_25_fu_976_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_25_reg_1494 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1229_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln703_reg_1500 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal grp_fu_1243_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln703_2_reg_1505 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal mul_ln1118_4_fu_1030_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1118_4_reg_1510 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1118_5_fu_1039_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1118_5_reg_1516 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_s_reg_1522 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_5_fu_1137_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_5_reg_1528 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_1_reg_1533 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_reg_1539 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter1_state4 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal k_buf_0_val_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce0 : STD_LOGIC;
    signal k_buf_0_val_3_we0 : STD_LOGIC;
    signal k_buf_0_val_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_3_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce1 : STD_LOGIC;
    signal k_buf_0_val_3_we1 : STD_LOGIC;
    signal k_buf_0_val_4_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce0 : STD_LOGIC;
    signal k_buf_0_val_4_we0 : STD_LOGIC;
    signal k_buf_0_val_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_4_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce1 : STD_LOGIC;
    signal k_buf_0_val_4_we1 : STD_LOGIC;
    signal k_buf_0_val_5_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce0 : STD_LOGIC;
    signal k_buf_0_val_5_we0 : STD_LOGIC;
    signal k_buf_0_val_5_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce1 : STD_LOGIC;
    signal k_buf_0_val_5_we1 : STD_LOGIC;
    signal t_V_reg_308 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal zext_ln835_fu_814_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal src_kernel_win_0_va_fu_144 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_18_fu_148 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_19_fu_152 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_20_fu_156 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_21_fu_160 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_src_kernel_win_0_va_29 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_22_fu_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_src_kernel_win_0_va_30 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_s_fu_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_fu_852_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_14_fu_172 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_15_fu_176 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_16_fu_180 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_1_0_fu_870_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_17_fu_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_18_fu_188 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_2_0_fu_887_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_right_border_buf_0_19 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_382_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln443_fu_354_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln506_fu_420_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_28_fu_426_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln118_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln118_6_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_452_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln142_fu_460_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln139_1_fu_466_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln506_1_fu_484_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln506_2_fu_510_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln147_fu_480_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln144_1_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln507_fu_536_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln506_fu_416_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln118_1_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln507_fu_550_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln507_fu_542_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln507_1_fu_556_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln142_fu_506_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_31_fu_498_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln118_fu_576_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln118_fu_582_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_30_fu_490_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln139_4_fu_586_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln118_1_fu_570_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln118_fu_594_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln142_2_fu_532_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_33_fu_524_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln118_7_fu_614_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln118_2_fu_620_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_32_fu_516_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln139_5_fu_624_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln118_fu_608_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln118_1_fu_632_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_34_fu_662_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln444_fu_646_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_x_fu_678_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_35_fu_688_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln118_1_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln118_8_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_714_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln142_2_fu_722_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln139_fu_728_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln139_1_fu_740_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln451_fu_684_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln147_fu_750_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln118_3_fu_756_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln118_9_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln144_fu_744_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln118_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln144_fu_780_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln139_fu_736_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln118_fu_764_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln891_fu_672_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln144_fu_811_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_841_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_859_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_877_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_929_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_947_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_965_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1118_fu_989_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln1118_fu_993_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_1236_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1118_4_fu_1030_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_4_fu_1030_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln1118_5_fu_1039_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1118_5_fu_1039_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln703_3_fu_1083_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln703_5_fu_1089_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln703_4_fu_1094_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_1250_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln703_6_fu_1098_p2 : STD_LOGIC_VECTOR (11 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln703_6_fu_1098_p2 : signal is "no";
    signal zext_ln703_2_fu_1106_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_s_fu_1109_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln703_fu_1086_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln703_1_fu_1103_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln703_9_fu_1128_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln703_5_fu_1133_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln703_8_fu_1123_p2 : STD_LOGIC_VECTOR (11 downto 0);
    attribute use_dsp48 of add_ln703_8_fu_1123_p2 : signal is "no";
    signal or_ln785_fu_1162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln785_fu_1166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln786_fu_1177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln786_fu_1181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_1187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_1171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln340_fu_1192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln703_6_fu_1159_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln340_1_fu_1198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln340_fu_1204_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln388_fu_1212_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1229_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1229_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_1236_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1236_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_1243_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1243_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_1250_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1250_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_predicate_op144_store_state4 : BOOLEAN;
    signal ap_enable_operation_144 : BOOLEAN;
    signal ap_enable_state4_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op142_load_state4 : BOOLEAN;
    signal ap_enable_operation_142 : BOOLEAN;
    signal ap_enable_operation_167 : BOOLEAN;
    signal ap_enable_state5_pp0_iter2_stage0 : BOOLEAN;
    signal ap_predicate_op172_store_state5 : BOOLEAN;
    signal ap_enable_operation_172 : BOOLEAN;
    signal ap_predicate_op146_store_state4 : BOOLEAN;
    signal ap_enable_operation_146 : BOOLEAN;
    signal ap_enable_operation_140 : BOOLEAN;
    signal ap_enable_operation_164 : BOOLEAN;
    signal ap_predicate_op173_store_state5 : BOOLEAN;
    signal ap_enable_operation_173 : BOOLEAN;
    signal ap_predicate_op148_store_state4 : BOOLEAN;
    signal ap_enable_operation_148 : BOOLEAN;
    signal ap_enable_operation_137 : BOOLEAN;
    signal ap_enable_operation_161 : BOOLEAN;
    signal ap_predicate_op151_store_state4 : BOOLEAN;
    signal ap_enable_operation_151 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_1229_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_1236_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_1243_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_1250_p00 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_4_fu_1030_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1118_5_fu_1039_p00 : STD_LOGIC_VECTOR (10 downto 0);

    component sobel_accel_mux_3hbi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_accel_mac_mpcA IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (1 downto 0);
        din2 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component sobel_accel_mac_mqcK IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (1 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component sobel_accel_mac_mrcU IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component sobel_accel_mac_msc4 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component Filter2D_1_k_buf_eOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    k_buf_0_val_3_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_3_address0,
        ce0 => k_buf_0_val_3_ce0,
        we0 => k_buf_0_val_3_we0,
        d0 => p_src_data_stream_V_dout,
        q0 => k_buf_0_val_3_q0,
        address1 => k_buf_0_val_3_address1,
        ce1 => k_buf_0_val_3_ce1,
        we1 => k_buf_0_val_3_we1,
        d1 => p_src_data_stream_V_dout);

    k_buf_0_val_4_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_4_address0,
        ce0 => k_buf_0_val_4_ce0,
        we0 => k_buf_0_val_4_we0,
        d0 => p_src_data_stream_V_dout,
        q0 => k_buf_0_val_4_q0,
        address1 => k_buf_0_val_4_address1,
        ce1 => k_buf_0_val_4_ce1,
        we1 => k_buf_0_val_4_we1,
        d1 => k_buf_0_val_3_q0);

    k_buf_0_val_5_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_5_address0,
        ce0 => k_buf_0_val_5_ce0,
        we0 => k_buf_0_val_5_we0,
        d0 => p_src_data_stream_V_dout,
        q0 => k_buf_0_val_5_q0,
        address1 => k_buf_0_val_5_address1,
        ce1 => k_buf_0_val_5_ce1,
        we1 => k_buf_0_val_5_we1,
        d1 => k_buf_0_val_4_q0);

    sobel_accel_mux_3hbi_U55 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_s_fu_168,
        din1 => right_border_buf_0_14_fu_172,
        din2 => ap_const_lv8_0,
        din3 => xor_ln493_reg_1462,
        dout => tmp_4_fu_841_p5);

    sobel_accel_mux_3hbi_U56 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_16_fu_180,
        din1 => right_border_buf_0_17_fu_184,
        din2 => ap_const_lv8_0,
        din3 => xor_ln493_reg_1462,
        dout => tmp_5_fu_859_p5);

    sobel_accel_mux_3hbi_U57 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_19_reg_1451,
        din1 => right_border_buf_0_15_fu_176,
        din2 => ap_const_lv8_0,
        din3 => xor_ln493_reg_1462,
        dout => tmp_6_fu_877_p5);

    sobel_accel_mux_3hbi_U58 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_852_p3,
        din1 => col_buf_0_val_1_0_fu_870_p3,
        din2 => col_buf_0_val_2_0_fu_887_p3,
        din3 => xor_ln493_1_reg_1402,
        dout => tmp_7_fu_929_p5);

    sobel_accel_mux_3hbi_U59 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_852_p3,
        din1 => col_buf_0_val_1_0_fu_870_p3,
        din2 => col_buf_0_val_2_0_fu_887_p3,
        din3 => xor_ln493_2_reg_1407,
        dout => tmp_8_fu_947_p5);

    sobel_accel_mux_3hbi_U60 : component sobel_accel_mux_3hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_852_p3,
        din1 => col_buf_0_val_1_0_fu_870_p3,
        din2 => col_buf_0_val_2_0_fu_887_p3,
        din3 => xor_ln493_3_reg_1412,
        dout => tmp_9_fu_965_p5);

    sobel_accel_mac_mpcA_U61 : component sobel_accel_mac_mpcA
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 2,
        din2_WIDTH => 9,
        dout_WIDTH => 11)
    port map (
        din0 => grp_fu_1229_p0,
        din1 => grp_fu_1229_p1,
        din2 => sub_ln1118_fu_993_p2,
        dout => grp_fu_1229_p3);

    sobel_accel_mac_mqcK_U62 : component sobel_accel_mac_mqcK
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 2,
        din2_WIDTH => 11,
        dout_WIDTH => 11)
    port map (
        din0 => grp_fu_1236_p0,
        din1 => grp_fu_1236_p1,
        din2 => add_ln703_reg_1500,
        dout => grp_fu_1236_p3);

    sobel_accel_mac_mrcU_U63 : component sobel_accel_mac_mrcU
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 3,
        din2_WIDTH => 11,
        dout_WIDTH => 12)
    port map (
        din0 => grp_fu_1243_p0,
        din1 => grp_fu_1243_p1,
        din2 => grp_fu_1236_p3,
        dout => grp_fu_1243_p3);

    sobel_accel_mac_msc4_U64 : component sobel_accel_mac_msc4
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 4,
        din2_WIDTH => 12,
        dout_WIDTH => 12)
    port map (
        din0 => grp_fu_1250_p0,
        din1 => grp_fu_1250_p1,
        din2 => add_ln703_2_reg_1505,
        dout => grp_fu_1250_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((icmp_ln444_fu_650_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln443_fu_358_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter1_state4)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif (((icmp_ln443_fu_358_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    t_V_2_reg_319_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln444_fu_650_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                t_V_2_reg_319 <= j_V_fu_656_p2;
            elsif (((icmp_ln443_fu_358_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_V_2_reg_319 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    t_V_reg_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                t_V_reg_308 <= i_V_reg_1368;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_reg_308 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter2_reg) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln703_2_reg_1505 <= grp_fu_1243_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter1_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln703_reg_1500 <= grp_fu_1229_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln444_fu_650_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln118_reg_1426 <= and_ln118_fu_708_p2;
                and_ln512_reg_1447 <= and_ln512_fu_803_p2;
                or_ln457_reg_1440 <= or_ln457_fu_798_p2;
                trunc_ln458_reg_1435 <= trunc_ln458_fu_794_p1;
                x_reg_1430 <= x_fu_786_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln118_reg_1426_pp0_iter1_reg <= and_ln118_reg_1426;
                and_ln512_reg_1447_pp0_iter1_reg <= and_ln512_reg_1447;
                icmp_ln444_reg_1417 <= icmp_ln444_fu_650_p2;
                icmp_ln444_reg_1417_pp0_iter1_reg <= icmp_ln444_reg_1417;
                or_ln457_reg_1440_pp0_iter1_reg <= or_ln457_reg_1440;
                right_border_buf_0_19_reg_1451 <= ap_sig_allocacmp_right_border_buf_0_19;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln512_reg_1447_pp0_iter2_reg <= and_ln512_reg_1447_pp0_iter1_reg;
                and_ln512_reg_1447_pp0_iter3_reg <= and_ln512_reg_1447_pp0_iter2_reg;
                and_ln512_reg_1447_pp0_iter4_reg <= and_ln512_reg_1447_pp0_iter3_reg;
                icmp_ln444_reg_1417_pp0_iter2_reg <= icmp_ln444_reg_1417_pp0_iter1_reg;
                src_kernel_win_0_va_23_reg_1481 <= src_kernel_win_0_va_23_fu_940_p3;
                src_kernel_win_0_va_23_reg_1481_pp0_iter3_reg <= src_kernel_win_0_va_23_reg_1481;
                src_kernel_win_0_va_24_reg_1488 <= src_kernel_win_0_va_24_fu_958_p3;
                src_kernel_win_0_va_24_reg_1488_pp0_iter3_reg <= src_kernel_win_0_va_24_reg_1488;
                src_kernel_win_0_va_25_reg_1494 <= src_kernel_win_0_va_25_fu_976_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_V_reg_1368 <= i_V_fu_364_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln443_fu_358_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln879_1_reg_1391 <= icmp_ln879_1_fu_404_p2;
                icmp_ln879_reg_1387 <= icmp_ln879_fu_398_p2;
                icmp_ln887_reg_1373 <= icmp_ln887_fu_370_p2;
                icmp_ln899_1_reg_1395 <= icmp_ln899_1_fu_410_p2;
                icmp_ln899_reg_1382 <= icmp_ln899_fu_392_p2;
                xor_ln457_reg_1377 <= xor_ln457_fu_376_p2;
                xor_ln493_1_reg_1402 <= xor_ln493_1_fu_564_p2;
                xor_ln493_2_reg_1407 <= xor_ln493_2_fu_602_p2;
                xor_ln493_3_reg_1412 <= xor_ln493_3_fu_640_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                k_buf_0_val_4_addr_reg_1469 <= zext_ln835_fu_814_p1(11 - 1 downto 0);
                k_buf_0_val_5_addr_reg_1475 <= zext_ln835_fu_814_p1(11 - 1 downto 0);
                xor_ln493_reg_1462 <= xor_ln493_fu_821_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter2_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln1118_4_reg_1510 <= mul_ln1118_4_fu_1030_p2;
                mul_ln1118_5_reg_1516 <= mul_ln1118_5_fu_1039_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter3_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_Result_1_reg_1533 <= p_Val2_5_fu_1137_p2(11 downto 11);
                p_Result_s_reg_1522 <= p_Val2_s_fu_1109_p2(11 downto 11);
                p_Val2_5_reg_1528 <= p_Val2_5_fu_1137_p2;
                tmp_41_reg_1539 <= p_Val2_s_fu_1109_p2(11 downto 11);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426_pp0_iter1_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                right_border_buf_0_14_fu_172 <= right_border_buf_0_s_fu_168;
                right_border_buf_0_15_fu_176 <= right_border_buf_0_19_reg_1451;
                right_border_buf_0_16_fu_180 <= col_buf_0_val_1_0_fu_870_p3;
                right_border_buf_0_17_fu_184 <= right_border_buf_0_16_fu_180;
                right_border_buf_0_18_fu_188 <= col_buf_0_val_2_0_fu_887_p3;
                right_border_buf_0_s_fu_168 <= col_buf_0_val_0_0_fu_852_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                sext_ln1118_1_reg_1339 <= sext_ln1118_1_fu_334_p1;
                sext_ln1118_2_reg_1344 <= sext_ln1118_2_fu_338_p1;
                sext_ln1118_3_reg_1354 <= sext_ln1118_3_fu_346_p1;
                sext_ln1118_reg_1334 <= sext_ln1118_fu_330_p1;
                    zext_ln1118_4_reg_1349(3 downto 0) <= zext_ln1118_4_fu_342_p1(3 downto 0);
                    zext_ln1118_5_reg_1359(2 downto 0) <= zext_ln1118_5_fu_350_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln444_reg_1417_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                src_kernel_win_0_va_18_fu_148 <= src_kernel_win_0_va_fu_144;
                src_kernel_win_0_va_19_fu_152 <= src_kernel_win_0_va_24_reg_1488;
                src_kernel_win_0_va_20_fu_156 <= src_kernel_win_0_va_19_fu_152;
                src_kernel_win_0_va_21_fu_160 <= src_kernel_win_0_va_25_reg_1494;
                src_kernel_win_0_va_22_fu_164 <= src_kernel_win_0_va_21_fu_160;
                src_kernel_win_0_va_fu_144 <= src_kernel_win_0_va_23_reg_1481;
            end if;
        end if;
    end process;
    zext_ln1118_4_reg_1349(11 downto 4) <= "00000000";
    zext_ln1118_5_reg_1359(10 downto 3) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, icmp_ln443_fu_358_p2, ap_CS_fsm_state2, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln443_fu_358_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ImagLoc_x_fu_678_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(zext_ln444_fu_646_p1));
    add_ln118_fu_608_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(trunc_ln506_fu_416_p1));
    add_ln506_1_fu_484_p2 <= std_logic_vector(signed(ap_const_lv12_FFE) + signed(zext_ln443_fu_354_p1));
    add_ln506_2_fu_510_p2 <= std_logic_vector(signed(ap_const_lv12_FFD) + signed(zext_ln443_fu_354_p1));
    add_ln506_fu_420_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(zext_ln443_fu_354_p1));
    add_ln507_fu_550_p2 <= std_logic_vector(signed(ap_const_lv2_3) + signed(trunc_ln506_fu_416_p1));
    add_ln703_5_fu_1089_p2 <= std_logic_vector(unsigned(mul_ln1118_5_reg_1516) + unsigned(sext_ln703_3_fu_1083_p1));
    add_ln703_6_fu_1098_p2 <= std_logic_vector(signed(sext_ln703_4_fu_1094_p1) + signed(grp_fu_1250_p3));
    add_ln703_8_fu_1123_p2 <= std_logic_vector(signed(grp_fu_1250_p3) + signed(zext_ln703_fu_1086_p1));
    add_ln703_9_fu_1128_p2 <= std_logic_vector(signed(mul_ln1118_4_reg_1510) + signed(zext_ln703_1_fu_1103_p1));
    and_ln118_1_fu_446_p2 <= (xor_ln118_6_fu_434_p2 and icmp_ln118_fu_440_p2);
    and_ln118_fu_708_p2 <= (xor_ln118_8_fu_696_p2 and icmp_ln118_1_fu_702_p2);
    and_ln144_fu_780_p2 <= (or_ln118_fu_774_p2 and icmp_ln144_fu_744_p2);
    and_ln512_fu_803_p2 <= (icmp_ln899_reg_1382 and icmp_ln891_fu_672_p2);
    and_ln786_fu_1177_p2 <= (tmp_41_reg_1539 and p_Result_1_reg_1533);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state9 <= ap_CS_fsm(3);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, and_ln512_reg_1447_pp0_iter4_reg, ap_predicate_op143_read_state4, ap_predicate_op150_read_state4)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter4_reg) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op150_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op143_read_state4 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, and_ln512_reg_1447_pp0_iter4_reg, ap_predicate_op143_read_state4, ap_predicate_op150_read_state4)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter4_reg) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op150_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op143_read_state4 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, and_ln512_reg_1447_pp0_iter4_reg, ap_predicate_op143_read_state4, ap_predicate_op150_read_state4)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter4_reg) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op150_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op143_read_state4 = ap_const_boolean_1)))));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(p_src_data_stream_V_empty_n, ap_predicate_op143_read_state4, ap_predicate_op150_read_state4)
    begin
                ap_block_state4_pp0_stage0_iter1 <= (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op150_read_state4 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op143_read_state4 = ap_const_boolean_1)));
    end process;

        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter5_assign_proc : process(p_dst_data_stream_V_full_n, and_ln512_reg_1447_pp0_iter4_reg)
    begin
                ap_block_state8_pp0_stage0_iter5 <= ((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter4_reg) and (p_dst_data_stream_V_full_n = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter1_state4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter1_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter1_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln443_fu_358_p2, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln443_fu_358_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_operation_137_assign_proc : process(icmp_ln444_reg_1417)
    begin
                ap_enable_operation_137 <= (icmp_ln444_reg_1417 = ap_const_lv1_0);
    end process;


    ap_enable_operation_140_assign_proc : process(icmp_ln444_reg_1417)
    begin
                ap_enable_operation_140 <= (icmp_ln444_reg_1417 = ap_const_lv1_0);
    end process;


    ap_enable_operation_142_assign_proc : process(ap_predicate_op142_load_state4)
    begin
                ap_enable_operation_142 <= (ap_predicate_op142_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_144_assign_proc : process(ap_predicate_op144_store_state4)
    begin
                ap_enable_operation_144 <= (ap_predicate_op144_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_146_assign_proc : process(ap_predicate_op146_store_state4)
    begin
                ap_enable_operation_146 <= (ap_predicate_op146_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_148_assign_proc : process(ap_predicate_op148_store_state4)
    begin
                ap_enable_operation_148 <= (ap_predicate_op148_store_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_151_assign_proc : process(ap_predicate_op151_store_state4)
    begin
                ap_enable_operation_151 <= (ap_predicate_op151_store_state4 = ap_const_boolean_1);
    end process;

        ap_enable_operation_161 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_164 <= (ap_const_boolean_1 = ap_const_boolean_1);

    ap_enable_operation_167_assign_proc : process(or_ln457_reg_1440_pp0_iter1_reg)
    begin
                ap_enable_operation_167 <= (or_ln457_reg_1440_pp0_iter1_reg = ap_const_lv1_1);
    end process;


    ap_enable_operation_172_assign_proc : process(ap_predicate_op172_store_state5)
    begin
                ap_enable_operation_172 <= (ap_predicate_op172_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_173_assign_proc : process(ap_predicate_op173_store_state5)
    begin
                ap_enable_operation_173 <= (ap_predicate_op173_store_state5 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_state4_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state4_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state5_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state5_pp0_iter2_stage0 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op142_load_state4_assign_proc : process(icmp_ln444_reg_1417, or_ln457_reg_1440)
    begin
                ap_predicate_op142_load_state4 <= ((or_ln457_reg_1440 = ap_const_lv1_1) and (icmp_ln444_reg_1417 = ap_const_lv1_0));
    end process;


    ap_predicate_op143_read_state4_assign_proc : process(icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382)
    begin
                ap_predicate_op143_read_state4 <= ((ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln899_reg_1382 = ap_const_lv1_0) and (icmp_ln444_reg_1417 = ap_const_lv1_0));
    end process;


    ap_predicate_op144_store_state4_assign_proc : process(icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln879_reg_1387)
    begin
                ap_predicate_op144_store_state4 <= ((icmp_ln879_reg_1387 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln899_reg_1382 = ap_const_lv1_0) and (icmp_ln444_reg_1417 = ap_const_lv1_0));
    end process;


    ap_predicate_op146_store_state4_assign_proc : process(icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln879_1_reg_1391)
    begin
                ap_predicate_op146_store_state4 <= ((icmp_ln879_1_reg_1391 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln899_reg_1382 = ap_const_lv1_0) and (icmp_ln444_reg_1417 = ap_const_lv1_0));
    end process;


    ap_predicate_op148_store_state4_assign_proc : process(icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln879_reg_1387)
    begin
                ap_predicate_op148_store_state4 <= ((icmp_ln879_reg_1387 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln899_reg_1382 = ap_const_lv1_0) and (icmp_ln444_reg_1417 = ap_const_lv1_0));
    end process;


    ap_predicate_op150_read_state4_assign_proc : process(icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln887_reg_1373)
    begin
                ap_predicate_op150_read_state4 <= ((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln444_reg_1417 = ap_const_lv1_0));
    end process;


    ap_predicate_op151_store_state4_assign_proc : process(icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln887_reg_1373)
    begin
                ap_predicate_op151_store_state4 <= ((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln444_reg_1417 = ap_const_lv1_0));
    end process;


    ap_predicate_op172_store_state5_assign_proc : process(icmp_ln899_reg_1382, icmp_ln887_reg_1373, and_ln118_reg_1426_pp0_iter1_reg)
    begin
                ap_predicate_op172_store_state5 <= ((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426_pp0_iter1_reg));
    end process;


    ap_predicate_op173_store_state5_assign_proc : process(icmp_ln899_reg_1382, icmp_ln887_reg_1373, and_ln118_reg_1426_pp0_iter1_reg)
    begin
                ap_predicate_op173_store_state5 <= ((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426_pp0_iter1_reg));
    end process;


    ap_ready_assign_proc : process(icmp_ln443_fu_358_p2, ap_CS_fsm_state2)
    begin
        if (((icmp_ln443_fu_358_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_right_border_buf_0_19_assign_proc : process(ap_block_pp0_stage0, icmp_ln899_reg_1382, icmp_ln887_reg_1373, and_ln118_reg_1426_pp0_iter1_reg, ap_enable_reg_pp0_iter2, right_border_buf_0_18_fu_188, col_buf_0_val_2_0_fu_887_p3)
    begin
        if (((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_sig_allocacmp_right_border_buf_0_19 <= col_buf_0_val_2_0_fu_887_p3;
        else 
            ap_sig_allocacmp_right_border_buf_0_19 <= right_border_buf_0_18_fu_188;
        end if; 
    end process;


    ap_sig_allocacmp_src_kernel_win_0_va_29_assign_proc : process(ap_block_pp0_stage0, icmp_ln444_reg_1417_pp0_iter2_reg, src_kernel_win_0_va_25_reg_1494, ap_enable_reg_pp0_iter3, src_kernel_win_0_va_21_fu_160)
    begin
        if (((icmp_ln444_reg_1417_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_src_kernel_win_0_va_29 <= src_kernel_win_0_va_25_reg_1494;
        else 
            ap_sig_allocacmp_src_kernel_win_0_va_29 <= src_kernel_win_0_va_21_fu_160;
        end if; 
    end process;


    ap_sig_allocacmp_src_kernel_win_0_va_30_assign_proc : process(ap_block_pp0_stage0, icmp_ln444_reg_1417_pp0_iter2_reg, ap_enable_reg_pp0_iter3, src_kernel_win_0_va_21_fu_160, src_kernel_win_0_va_22_fu_164)
    begin
        if (((icmp_ln444_reg_1417_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_sig_allocacmp_src_kernel_win_0_va_30 <= src_kernel_win_0_va_21_fu_160;
        else 
            ap_sig_allocacmp_src_kernel_win_0_va_30 <= src_kernel_win_0_va_22_fu_164;
        end if; 
    end process;

    col_buf_0_val_0_0_fu_852_p3 <= 
        k_buf_0_val_3_q0 when (or_ln457_reg_1440_pp0_iter1_reg(0) = '1') else 
        tmp_4_fu_841_p5;
    col_buf_0_val_1_0_fu_870_p3 <= 
        k_buf_0_val_4_q0 when (or_ln457_reg_1440_pp0_iter1_reg(0) = '1') else 
        tmp_5_fu_859_p5;
    col_buf_0_val_2_0_fu_887_p3 <= 
        k_buf_0_val_5_q0 when (or_ln457_reg_1440_pp0_iter1_reg(0) = '1') else 
        tmp_6_fu_877_p5;
    grp_fu_1229_p0 <= grp_fu_1229_p00(8 - 1 downto 0);
    grp_fu_1229_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_src_kernel_win_0_va_29),10));
    grp_fu_1229_p1 <= sext_ln1118_reg_1334(2 - 1 downto 0);
    grp_fu_1236_p0 <= grp_fu_1236_p00(8 - 1 downto 0);
    grp_fu_1236_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_25_reg_1494),10));
    grp_fu_1236_p1 <= sext_ln1118_1_reg_1339(2 - 1 downto 0);
    grp_fu_1243_p0 <= grp_fu_1243_p00(8 - 1 downto 0);
    grp_fu_1243_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_20_fu_156),11));
    grp_fu_1243_p1 <= sext_ln1118_2_reg_1344(3 - 1 downto 0);
    grp_fu_1250_p0 <= grp_fu_1250_p00(8 - 1 downto 0);
    grp_fu_1250_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_24_reg_1488_pp0_iter3_reg),12));
    grp_fu_1250_p1 <= zext_ln1118_4_reg_1349(4 - 1 downto 0);
    i_V_fu_364_p2 <= std_logic_vector(unsigned(t_V_reg_308) + unsigned(ap_const_lv11_1));
    icmp_ln118_1_fu_702_p2 <= "1" when (signed(ImagLoc_x_fu_678_p2) < signed(ap_const_lv12_780)) else "0";
    icmp_ln118_fu_440_p2 <= "1" when (signed(add_ln506_fu_420_p2) < signed(ap_const_lv12_438)) else "0";
    icmp_ln144_1_fu_474_p2 <= "1" when (signed(select_ln139_1_fu_466_p3) < signed(ap_const_lv12_438)) else "0";
    icmp_ln144_fu_744_p2 <= "1" when (signed(select_ln139_fu_728_p3) < signed(ap_const_lv12_780)) else "0";
    icmp_ln443_fu_358_p2 <= "1" when (t_V_reg_308 = ap_const_lv11_43A) else "0";
    icmp_ln444_fu_650_p2 <= "1" when (t_V_2_reg_319 = ap_const_lv11_782) else "0";
    icmp_ln879_1_fu_404_p2 <= "1" when (t_V_reg_308 = ap_const_lv11_0) else "0";
    icmp_ln879_fu_398_p2 <= "1" when (t_V_reg_308 = ap_const_lv11_1) else "0";
    icmp_ln887_fu_370_p2 <= "1" when (unsigned(t_V_reg_308) < unsigned(ap_const_lv11_438)) else "0";
    icmp_ln891_fu_672_p2 <= "0" when (tmp_34_fu_662_p4 = ap_const_lv10_0) else "1";
    icmp_ln899_1_fu_410_p2 <= "1" when (unsigned(t_V_reg_308) > unsigned(ap_const_lv11_438)) else "0";
    icmp_ln899_fu_392_p2 <= "0" when (tmp_fu_382_p4 = ap_const_lv10_0) else "1";
    j_V_fu_656_p2 <= std_logic_vector(unsigned(t_V_2_reg_319) + unsigned(ap_const_lv11_1));
    k_buf_0_val_3_address0 <= zext_ln835_fu_814_p1(11 - 1 downto 0);
    k_buf_0_val_3_address1 <= zext_ln835_fu_814_p1(11 - 1 downto 0);

    k_buf_0_val_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1417, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln879_reg_1387, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln879_reg_1387 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln899_reg_1382 = ap_const_lv1_0) and (icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_we0 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln887_reg_1373, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_4_address0 <= zext_ln835_fu_814_p1(11 - 1 downto 0);
    k_buf_0_val_4_address1 <= k_buf_0_val_4_addr_reg_1469;

    k_buf_0_val_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1417, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln879_1_reg_1391, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln879_1_reg_1391 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln899_reg_1382 = ap_const_lv1_0) and (icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_we0 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_we1_assign_proc : process(icmp_ln899_reg_1382, icmp_ln887_reg_1373, ap_block_pp0_stage0_11001, and_ln118_reg_1426_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426_pp0_iter1_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_5_address0 <= zext_ln835_fu_814_p1(11 - 1 downto 0);
    k_buf_0_val_5_address1 <= k_buf_0_val_5_addr_reg_1475;

    k_buf_0_val_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln879_reg_1387, ap_block_pp0_stage0_11001, or_ln457_reg_1440)
    begin
        if ((((icmp_ln879_reg_1387 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln899_reg_1382 = ap_const_lv1_0) and (icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((or_ln457_reg_1440 = ap_const_lv1_1) and (icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_5_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_5_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln879_reg_1387, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln879_reg_1387 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln899_reg_1382 = ap_const_lv1_0) and (icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_5_we0 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_we1_assign_proc : process(icmp_ln899_reg_1382, icmp_ln887_reg_1373, ap_block_pp0_stage0_11001, and_ln118_reg_1426_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426_pp0_iter1_reg) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_5_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln1118_4_fu_1030_p0 <= mul_ln1118_4_fu_1030_p00(8 - 1 downto 0);
    mul_ln1118_4_fu_1030_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_18_fu_148),10));
    mul_ln1118_4_fu_1030_p1 <= sext_ln1118_3_reg_1354(2 - 1 downto 0);
    mul_ln1118_4_fu_1030_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &mul_ln1118_4_fu_1030_p0) * signed(mul_ln1118_4_fu_1030_p1))), 10));
    mul_ln1118_5_fu_1039_p0 <= mul_ln1118_5_fu_1039_p00(8 - 1 downto 0);
    mul_ln1118_5_fu_1039_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_fu_144),11));
    mul_ln1118_5_fu_1039_p1 <= zext_ln1118_5_reg_1359(3 - 1 downto 0);
    mul_ln1118_5_fu_1039_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1118_5_fu_1039_p0) * unsigned(mul_ln1118_5_fu_1039_p1), 11));
    or_ln118_fu_774_p2 <= (xor_ln118_9_fu_768_p2 or tmp_35_fu_688_p3);
    or_ln340_1_fu_1198_p2 <= (xor_ln785_fu_1166_p2 or and_ln786_fu_1177_p2);
    or_ln340_fu_1192_p2 <= (underflow_fu_1187_p2 or overflow_fu_1171_p2);
    or_ln457_fu_798_p2 <= (xor_ln457_reg_1377 or icmp_ln118_1_fu_702_p2);
    or_ln785_fu_1162_p2 <= (tmp_41_reg_1539 or p_Result_1_reg_1533);
    overflow_fu_1171_p2 <= (xor_ln785_fu_1166_p2 and or_ln785_fu_1162_p2);
    p_Val2_5_fu_1137_p2 <= std_logic_vector(signed(sext_ln703_5_fu_1133_p1) + signed(add_ln703_8_fu_1123_p2));
    p_Val2_s_fu_1109_p2 <= std_logic_vector(unsigned(add_ln703_6_fu_1098_p2) + unsigned(zext_ln703_2_fu_1106_p1));

    p_dst_data_stream_V_blk_n_assign_proc : process(p_dst_data_stream_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter5, and_ln512_reg_1447_pp0_iter4_reg)
    begin
        if (((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter4_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_dst_data_stream_V_blk_n <= p_dst_data_stream_V_full_n;
        else 
            p_dst_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_data_stream_V_din <= 
        select_ln340_fu_1204_p3 when (or_ln340_1_fu_1198_p2(0) = '1') else 
        select_ln388_fu_1212_p3;

    p_dst_data_stream_V_write_assign_proc : process(ap_enable_reg_pp0_iter5, and_ln512_reg_1447_pp0_iter4_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_1 = and_ln512_reg_1447_pp0_iter4_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src_data_stream_V_blk_n_assign_proc : process(p_src_data_stream_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln444_reg_1417, and_ln118_reg_1426, icmp_ln899_reg_1382, icmp_ln887_reg_1373)
    begin
        if ((((icmp_ln887_reg_1373 = ap_const_lv1_1) and (icmp_ln899_reg_1382 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_lv1_1 = and_ln118_reg_1426) and (icmp_ln899_reg_1382 = ap_const_lv1_0) and (icmp_ln444_reg_1417 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_src_data_stream_V_blk_n <= p_src_data_stream_V_empty_n;
        else 
            p_src_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_data_stream_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op143_read_state4, ap_predicate_op150_read_state4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op150_read_state4 = ap_const_boolean_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op143_read_state4 = ap_const_boolean_1)))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln118_1_fu_632_p3 <= 
        select_ln139_5_fu_624_p3 when (tmp_32_fu_516_p3(0) = '1') else 
        add_ln118_fu_608_p2;
    select_ln118_3_fu_756_p3 <= 
        sext_ln451_fu_684_p1 when (and_ln118_fu_708_p2(0) = '1') else 
        sub_ln147_fu_750_p2;
    select_ln118_fu_594_p3 <= 
        select_ln139_4_fu_586_p3 when (tmp_30_fu_490_p3(0) = '1') else 
        xor_ln118_1_fu_570_p2;
    select_ln139_1_fu_466_p3 <= 
        sub_ln142_fu_460_p2 when (tmp_29_fu_452_p3(0) = '1') else 
        add_ln506_fu_420_p2;
    select_ln139_4_fu_586_p3 <= 
        sub_ln118_fu_576_p2 when (tmp_31_fu_498_p3(0) = '1') else 
        trunc_ln118_fu_582_p1;
    select_ln139_5_fu_624_p3 <= 
        xor_ln118_7_fu_614_p2 when (tmp_33_fu_524_p3(0) = '1') else 
        trunc_ln118_2_fu_620_p1;
    select_ln139_fu_728_p3 <= 
        sub_ln142_2_fu_722_p2 when (tmp_36_fu_714_p3(0) = '1') else 
        ImagLoc_x_fu_678_p2;
    select_ln340_fu_1204_p3 <= 
        ap_const_lv16_7FFF when (or_ln340_fu_1192_p2(0) = '1') else 
        sext_ln703_6_fu_1159_p1;
    select_ln388_fu_1212_p3 <= 
        ap_const_lv16_8000 when (underflow_fu_1187_p2(0) = '1') else 
        sext_ln703_6_fu_1159_p1;
    select_ln507_1_fu_556_p3 <= 
        add_ln507_fu_550_p2 when (and_ln118_1_fu_446_p2(0) = '1') else 
        select_ln507_fu_542_p3;
    select_ln507_fu_542_p3 <= 
        trunc_ln147_fu_480_p1 when (icmp_ln144_1_fu_474_p2(0) = '1') else 
        sub_ln507_fu_536_p2;
        sext_ln1118_1_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_kernel_val_0_V_2_read),10));

        sext_ln1118_2_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_kernel_val_1_V_0_read),11));

        sext_ln1118_3_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_kernel_val_2_V_0_read),10));

        sext_ln1118_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_kernel_val_0_V_1_read),10));

        sext_ln139_1_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln139_fu_728_p3),13));

        sext_ln139_fu_736_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln139_fu_728_p3),14));

        sext_ln144_fu_811_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_reg_1430),32));

        sext_ln451_fu_684_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ImagLoc_x_fu_678_p2),13));

        sext_ln703_3_fu_1083_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1118_4_reg_1510),11));

        sext_ln703_4_fu_1094_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln703_5_fu_1089_p2),12));

        sext_ln703_5_fu_1133_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln703_9_fu_1128_p2),12));

        sext_ln703_6_fu_1159_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_5_reg_1528),16));

    src_kernel_win_0_va_23_fu_940_p3 <= 
        tmp_7_fu_929_p5 when (icmp_ln899_1_reg_1395(0) = '1') else 
        col_buf_0_val_0_0_fu_852_p3;
    src_kernel_win_0_va_24_fu_958_p3 <= 
        tmp_8_fu_947_p5 when (icmp_ln899_1_reg_1395(0) = '1') else 
        col_buf_0_val_1_0_fu_870_p3;
    src_kernel_win_0_va_25_fu_976_p3 <= 
        tmp_9_fu_965_p5 when (icmp_ln899_1_reg_1395(0) = '1') else 
        col_buf_0_val_2_0_fu_887_p3;
    sub_ln1118_fu_993_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(zext_ln1118_fu_989_p1));
    sub_ln118_fu_576_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(trunc_ln142_fu_506_p1));
    sub_ln142_2_fu_722_p2 <= std_logic_vector(unsigned(ap_const_lv12_1) - unsigned(zext_ln444_fu_646_p1));
    sub_ln142_fu_460_p2 <= std_logic_vector(unsigned(ap_const_lv12_1) - unsigned(zext_ln443_fu_354_p1));
    sub_ln147_fu_750_p2 <= std_logic_vector(unsigned(ap_const_lv13_EFE) - unsigned(sext_ln139_1_fu_740_p1));
    sub_ln507_fu_536_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(trunc_ln147_fu_480_p1));
    tmp_28_fu_426_p3 <= add_ln506_fu_420_p2(11 downto 11);
    tmp_29_fu_452_p3 <= add_ln506_fu_420_p2(11 downto 11);
    tmp_30_fu_490_p3 <= add_ln506_1_fu_484_p2(11 downto 11);
    tmp_31_fu_498_p3 <= add_ln506_1_fu_484_p2(11 downto 11);
    tmp_32_fu_516_p3 <= add_ln506_2_fu_510_p2(11 downto 11);
    tmp_33_fu_524_p3 <= add_ln506_2_fu_510_p2(11 downto 11);
    tmp_34_fu_662_p4 <= t_V_2_reg_319(10 downto 1);
    tmp_35_fu_688_p3 <= ImagLoc_x_fu_678_p2(11 downto 11);
    tmp_36_fu_714_p3 <= ImagLoc_x_fu_678_p2(11 downto 11);
    tmp_fu_382_p4 <= t_V_reg_308(10 downto 1);
    trunc_ln118_2_fu_620_p1 <= add_ln506_2_fu_510_p2(2 - 1 downto 0);
    trunc_ln118_fu_582_p1 <= add_ln506_1_fu_484_p2(2 - 1 downto 0);
    trunc_ln142_2_fu_532_p1 <= t_V_reg_308(2 - 1 downto 0);
    trunc_ln142_fu_506_p1 <= t_V_reg_308(2 - 1 downto 0);
    trunc_ln147_fu_480_p1 <= select_ln139_1_fu_466_p3(2 - 1 downto 0);
    trunc_ln458_fu_794_p1 <= x_fu_786_p3(2 - 1 downto 0);
    trunc_ln506_fu_416_p1 <= t_V_reg_308(2 - 1 downto 0);
    underflow_fu_1187_p2 <= (xor_ln786_fu_1181_p2 and p_Result_s_reg_1522);
    x_fu_786_p3 <= 
        sext_ln139_fu_736_p1 when (and_ln144_fu_780_p2(0) = '1') else 
        zext_ln118_fu_764_p1;
    xor_ln118_1_fu_570_p2 <= (trunc_ln506_fu_416_p1 xor ap_const_lv2_2);
    xor_ln118_6_fu_434_p2 <= (tmp_28_fu_426_p3 xor ap_const_lv1_1);
    xor_ln118_7_fu_614_p2 <= (trunc_ln142_2_fu_532_p1 xor ap_const_lv2_3);
    xor_ln118_8_fu_696_p2 <= (tmp_35_fu_688_p3 xor ap_const_lv1_1);
    xor_ln118_9_fu_768_p2 <= (icmp_ln118_1_fu_702_p2 xor ap_const_lv1_1);
    xor_ln457_fu_376_p2 <= (icmp_ln887_fu_370_p2 xor ap_const_lv1_1);
    xor_ln493_1_fu_564_p2 <= (select_ln507_1_fu_556_p3 xor ap_const_lv2_3);
    xor_ln493_2_fu_602_p2 <= (select_ln118_fu_594_p3 xor ap_const_lv2_3);
    xor_ln493_3_fu_640_p2 <= (select_ln118_1_fu_632_p3 xor ap_const_lv2_3);
    xor_ln493_fu_821_p2 <= (trunc_ln458_reg_1435 xor ap_const_lv2_3);
    xor_ln785_fu_1166_p2 <= (p_Result_s_reg_1522 xor ap_const_lv1_1);
    xor_ln786_fu_1181_p2 <= (ap_const_lv1_1 xor and_ln786_fu_1177_p2);
    zext_ln1118_4_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_kernel_val_1_V_2_read),12));
    zext_ln1118_5_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_kernel_val_2_V_1_read),11));
    zext_ln1118_fu_989_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_src_kernel_win_0_va_30),9));
    zext_ln118_fu_764_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln118_3_fu_756_p3),14));
    zext_ln443_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_reg_308),12));
    zext_ln444_fu_646_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_2_reg_319),12));
    zext_ln703_1_fu_1103_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_23_reg_1481_pp0_iter3_reg),10));
    zext_ln703_2_fu_1106_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_23_reg_1481_pp0_iter3_reg),12));
    zext_ln703_fu_1086_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1118_5_reg_1516),12));
    zext_ln835_fu_814_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln144_fu_811_p1),64));
end behav;
