# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/base.xdc

# XDC: D:/DESKTOP/Integrated/lab4/4C1_Lab4_ZHaohan/PYNQ-image_v2.5.4/boards/Pynq-Z2/base/vivado/constraints/base.xdc

# Block Designs: bd/base/base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_processing_system7_0_0/base_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_processing_system7_0_0 || ORIG_REF_NAME==base_processing_system7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_0 || ORIG_REF_NAME==base_axi_vdma_0_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_vdma_1_0/base_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_vdma_1_0 || ORIG_REF_NAME==base_axi_vdma_1_0} -quiet] -quiet

# IP: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xlconcat_1_0/base_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xlconcat_1_0 || ORIG_REF_NAME==base_xlconcat_1_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_intc_0_0/base_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_intc_0_0 || ORIG_REF_NAME==base_axi_intc_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_11/base_xbar_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_xbar_11 || ORIG_REF_NAME==base_xbar_11} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_12/base_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_auto_pc_12 || ORIG_REF_NAME==base_auto_pc_12} -quiet] -quiet

# IP: bd/base/ip/base_s00_mmu_0/base_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_s00_mmu_0 || ORIG_REF_NAME==base_s00_mmu_0} -quiet] -quiet

# IP: bd/base/ip/base_axi_interconnect_1_0/base_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_axi_interconnect_1_0 || ORIG_REF_NAME==base_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/base/ip/base_smartconnect_0_0/base_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_smartconnect_0_0 || ORIG_REF_NAME==base_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/base/ip/base_smartconnect_0_0/bd_0/bd_b441.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_0/bd_b441_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_2/bd_b441_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_3/bd_b441_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_4/bd_b441_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_5/bd_b441_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_6/bd_b441_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_7/bd_b441_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_8/bd_b441_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_9/bd_b441_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_10/bd_b441_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_11/bd_b441_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_12/bd_b441_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_13/bd_b441_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_14/bd_b441_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_15/bd_b441_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_16/bd_b441_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_17/bd_b441_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_18/bd_b441_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_19/bd_b441_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_20/bd_b441_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_21/bd_b441_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_22/bd_b441_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_23/bd_b441_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_24/bd_b441_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_25/bd_b441_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_26/bd_b441_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_27/bd_b441_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_28/bd_b441_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_29/bd_b441_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_30/bd_b441_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_31/bd_b441_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_32/bd_b441_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_33/bd_b441_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_34/bd_b441_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_35/bd_b441_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_36/bd_b441_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_37/bd_b441_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_38/bd_b441_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_39/bd_b441_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/base/ip/base_sobel_accel_0_0/base_sobel_accel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_sobel_accel_0_0 || ORIG_REF_NAME==base_sobel_accel_0_0} -quiet] -quiet

# XDC: bd/base/ip/base_processing_system7_0_0/base_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_processing_system7_0_0 || ORIG_REF_NAME==base_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_0 || ORIG_REF_NAME==base_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_vdma_0_0 || ORIG_REF_NAME==base_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_vdma_0_0/base_axi_vdma_0_0_ooc.xdc

# XDC: bd/base/ip/base_axi_vdma_1_0/base_axi_vdma_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_vdma_1_0 || ORIG_REF_NAME==base_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_vdma_1_0/base_axi_vdma_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_vdma_1_0 || ORIG_REF_NAME==base_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_vdma_1_0/base_axi_vdma_1_0_ooc.xdc

# XDC: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_proc_sys_reset_0_0/base_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_proc_sys_reset_0_0 || ORIG_REF_NAME==base_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_intc_0_0/base_axi_intc_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_intc_0_0 || ORIG_REF_NAME==base_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_intc_0_0/base_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_axi_intc_0_0 || ORIG_REF_NAME==base_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base/ip/base_axi_intc_0_0/base_axi_intc_0_0_ooc.xdc

# XDC: bd/base/ip/base_auto_pc_12/base_auto_pc_12_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_1/bd_b441_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_2/bd_b441_arsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_3/bd_b441_rsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_4/bd_b441_awsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_5/bd_b441_wsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_6/bd_b441_bsw_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_10/bd_b441_s00a2s_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_11/bd_b441_sarn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_12/bd_b441_srn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_16/bd_b441_s01a2s_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_17/bd_b441_sawn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_18/bd_b441_swn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_19/bd_b441_sbn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_23/bd_b441_s02a2s_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_24/bd_b441_sarn_1_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_25/bd_b441_srn_1_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_29/bd_b441_s03a2s_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_30/bd_b441_sawn_1_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_31/bd_b441_swn_1_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_32/bd_b441_sbn_1_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_33/bd_b441_m00s2a_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_34/bd_b441_m00arn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_35/bd_b441_m00rn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_36/bd_b441_m00awn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_37/bd_b441_m00wn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/bd_0/ip/ip_38/bd_b441_m00bn_0_ooc.xdc

# XDC: bd/base/ip/base_smartconnect_0_0/ooc.xdc

# XDC: bd/base/ip/base_sobel_accel_0_0/constraints/sobel_accel_ooc.xdc

# XDC: bd/base/base_ooc.xdc
